#75: add English and Polish localizaton
projekt-inzynierski/survey-admin-panel pull request #23
Opened 2024-07-11 18:40 UTC by pawelFelcyn

This pull request refers to https://dev.azure.com/survey-project/Survey/_boards/board/t/Survey%20Team/Issues/?workitem=75 adds the following to the admin panel:
- English and Polish localization
- by default, it loads the browser language (if it is not English or Polish, it loads English)
- on the right side of the top bar, there is a picker that allows the user to change the selected language

2024-07-12 16:20 UTC, mikolaj4 requested changes
2 minor changes

2024-07-12 16:20 UTC, mikolaj4 commented on src/assets/i18n/pl.json
> +            "createRespondentsAccounts": "Utwórz konta dla respondentów",
It does not work while changing language to polish.

2024-07-12 16:20 UTC, mikolaj4 commented on src/presentation/modules/app/components/add-respondents/add-respondents.component.html
> +    <button mat-flat-button color="primary">{{ 'respondents.addRespondents.create' | translate }}z</button>
Typo with "z"

2024-07-16 18:39 UTC, pawelFelcyn commented on src/assets/i18n/pl.json
> +            "createRespondentsAccounts": "Utwórz konta dla respondentów",
it's fixed

2024-07-16 19:09 UTC, merged